[workspace]
members = [
    "services/identity-service/app",
    "services/course-service/app",
    "services/portal-service/app",
]
resolver = "2" # Usar el resolver m√°s moderno para mejores dependencias